### PR TITLE
Add ogg encoder block

### PR DESCRIPTION
**Pull request by GVardakis**

### CODE REVIEW

**Comment by surligas** [comment]
@GVardakis fix please the licence preamble and some identation issues at the CMakeLists files :)

**Comment by GVardakis** [comment]
r?

**Comment by GVardakis** [comment]
Finally ready for review @surligas

**Comment by cshields** [comment]
I'll test this out this weekend if nobody else beats me to it - would be nice to implement this and skip the oggenc step!

**Comment by surligas** [comment]
PR it at the dev branch

**Pull request closed without merging**
