### PR TITLE
Vardakis/json to ecss

### PR DESCRIPTION
**Pull request by GVardakis**
Apart from the work done on my block. i also changed a line in your udp_msg_source block because it was throwing a memory error.

### CODE REVIEW

**Comment by surligas** [comment]
Ok, some modifications before I accept your request:
1. Change the License at every new file
2. If you use `malloc()` at the destructor you have to use `free()` and not `delete`. Also, you have to check for errors. `new` will gracefully throw a bad alloc exception whereas `malloc()` not. But why did you get a memory error?

**Comment by GVardakis** [comment]
What license should I put?
I will paste you the error.It occurred at the message_port_pub function of udp_msg_source block.It said error in free().As soon as i removed the previous allocation method it worked like a charm

**Comment by surligas** [comment]
Just copy and paste the header licence that there is in all other files

**Comment by acinonyx** [comment]
Your pull request is full of backup files of unresolved conflicts at the moment. Remove the .orig files

**Comment by GVardakis** [comment]
The afformentioned changes are completed.
Manolis the error presented with memory was the following:
error1

And gdb gives this:

error2

**Comment by surligas** [comment]
The memory issue is now fixed.I prefer to stay with the `new` allocation mechanism of C++.

**Pull request merged**
