### PR TITLE
adding CW graph and script

### PR DESCRIPTION
**Pull request by cshields**
CW-specific gnuradio script. thanks to csete for contributing!

### CODE REVIEW

**Comment by cshields** [comment]
solves satnogs/gr-satnogs#52

**Comment by surligas** [comment]
I am accepting it for now and later we will change it with some ongoing work that we have already done. We have to take into account also some kind of CW transmissions that are modulated over an FM carrier.

Thanks!

**Comment by cshields** [comment]
> We have to take into account also some kind of CW transmissions that are modulated over an FM carrier.

Yes, those should be set with MCW as the mode ([modulated cw](https://github.com/satnogs/gr-satnogs/pull/75#issuecomment-299648995)). Looks like we don't have that as a mode in db today, but this would allow CW to be kept as just that, continuous wave.

**Comment by surligas** [comment]
The only difference should be the quadrature demodulation prior any cw operation, am I right?

**Comment by cshields** [comment]
As long as we are tuned to the demodulated pitch being where the decoder expects it (~700?) then there is no difference between the FM demodulation we do today and MCW.

So, to answer your question differently, correct, that is the only difference, and we already do that today in FM.  But, tagging transmitters in db that do MCW as MCW would prevent them from being demodulated as CW today. Do we have a list of those?

**Pull request merged**
